name: wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: ^1.1.6
  dependencies:
  salomon_bottom_bar: ^3.3.1
  google_fonts: ^4.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^7.0.1
  dio: ^5.0.0
  http: ^0.13.5
  image_picker: ^0.8.6+1
  http_parser: ^4.0.2
  intl: ^0.18.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

